# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='db_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='db_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 10, 14, 13, 56, 22, 548889, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(db_index=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 10, 14, 13, 56, 45, 845818, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(default=datetime.datetime(2017, 10, 14, 13, 56, 52, 621721, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
