# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20171014_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='details',
        ),
    ]
