# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_event_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
